version: 0.0
os: linux
files:
 - source: /app
   destination: /home/ec2-user/var/www/html/
 - source: requirements.txt
   destination: /home/ec2-user/var/www/html/
permissions:
  - object: /home/ec2-user/var/www/html/app/flaskrun.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/python-flask-service/flaskrun.py
    owner: ec2-user
    mode: 644
    type:
      - file
  - object: /home/ec2-user/var/www/html/requirements.txt
    owner: ec2-user
    mode: 644
    type:
      - file
  
hooks:
  AfterInstall:
   - location: /home/ec2-user/var/www/html/scripts/install_dependencies
     timeout: 300
     runas: root
   - location: scripts/start_server
     timeout: 300
     runas: root
  ApplicationStop:
   - location: /home/ec2-user/var/www/html/scripts/stop_server
     timeout: 300
     runas: root